language: python
# OS: Linux
dist: xenial
python:
  - "3.6"
  - "3.7"

matrix:
  include:
    # OS: Windows
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.6.8
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        # - pip3 install codecov
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH

    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.7.4
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        # - pip3 install codecov
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

# command to install dependencies
install:
  # - pip install codecov
  # - pip install coveralls
  - pip install -r requirements.txt
  - pip install -e .
# command to run tests
script:
  - coverage run --source optbinning -m pytest tests/

# after_success:
#   - codecov
#   - coveralls